### ISSUE TITLE
Composer Installation error

### ISSUE THREAD

**Issue by jjavierfg** [cloudcogsio/oauth2-openid-connect-discovery#1]
Hi, when I try to install the library using composer I get this error:

```
[InvalidArgumentException]
Could not find a version of package cloudcogsio / oauth2-openid-connect-discovery matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

Thanks!

**Comment by cloudcogsio** [comment]
Hi, your project's minimum stability is set to "stable". 

The library is still undergoing some changes before I consider shifting the minimum stability and doing a release. For now, it's still in "dev".

You can change your project's minimum-stability in your composer.json file to 'dev' and then you will be able to use it.

"minimum-stability" : "dev"
